-- Your SQL goes here
ALTER TABLE `events` ADD COLUMN `event_type` TEXT NOT NULL;
ALTER TABLE `events` ADD COLUMN `tag` TEXT;
ALTER TABLE `events` ADD COLUMN `status` TEXT NOT NULL;
ALTER TABLE `events` ADD COLUMN `original_text` TEXT;
ALTER TABLE `events` ADD COLUMN `importance` INTEGER NOT NULL;
ALTER TABLE `events` ADD COLUMN `load` INTEGER NOT NULL;
ALTER TABLE `events` ADD COLUMN `urgency` INTEGER NOT NULL;
ALTER TABLE `events` ADD COLUMN `postponed` INTEGER NOT NULL;

