-- Your SQL goes here
ALTER TABLE `todos` DROP COLUMN `url`; 
ALTER TABLE `todos` DROP COLUMN `etag`; 
ALTER TABLE `todos` ADD COLUMN `event_type` TEXT NOT NULL DEFAULT "task";
ALTER TABLE `todos` ADD COLUMN `tag` TEXT;
ALTER TABLE `todos` ADD COLUMN `status` TEXT NOT NULL DEFAULT "todo";
ALTER TABLE `todos` ADD COLUMN `original_text` TEXT;
ALTER TABLE `todos` ADD COLUMN `importance` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE `todos` ADD COLUMN `load` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE `todos` ADD COLUMN `urgency` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE `todos` ADD COLUMN `postponed` INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX uid_todos ON todos(uid)
